// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppPasswordsSystemCredential struct {
	Name        string
	Description string
	Nonce       []byte
	Ciphertext  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AppPasswordsSystemDataKey struct {
	Name             string
	EncryptedDataKey []byte
	CreatedAt        time.Time
}

type AppPasswordsUserCredential struct {
	UserID      string
	Name        string
	Description string
	Nonce       []byte
	Ciphertext  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AppPasswordsUserDataKey struct {
	UserID           string
	EncryptedDataKey []byte
	CreatedAt        time.Time
}

type AppPasswordsWorkspaceCredential struct {
	WorkspaceID string
	Name        string
	Description string
	Nonce       []byte
	Ciphertext  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AppPasswordsWorkspaceDataKey struct {
	WorkspaceID      string
	EncryptedDataKey []byte
	CreatedAt        time.Time
}
