// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO app_passwords_credentials (name, value, description)
VALUES ($1, $2, $3)
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

type CreateCredentialParams struct {
	Name        string
	Value       string
	Description string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (AppPasswordsCredential, error) {
	row := q.db.QueryRow(ctx, createCredential, arg.Name, arg.Value, arg.Description)
	var i AppPasswordsCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM app_passwords_credentials WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCredentialByName(ctx context.Context, name string) (AppPasswordsCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByName, name)
	var i AppPasswordsCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCredential = `-- name: SoftDeleteCredential :exec
UPDATE app_passwords_credentials SET deleted_at = now() WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCredential(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, softDeleteCredential, name)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE app_passwords_credentials
SET value = $1, description = $2, updated_at = now()
WHERE name = $3 AND deleted_at IS NULL
`

type UpdateCredentialParams struct {
	Value       string
	Description string
	Name        string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.Value, arg.Description, arg.Name)
	return err
}
