// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppSettingsSystem struct {
	Name      string
	Value     string
	UpdatedAt time.Time
}

type AppSettingsUser struct {
	UserID    string
	Name      string
	Value     string
	UpdatedAt time.Time
}

type AppSettingsWorkspace struct {
	WorkspaceID string
	Name        string
	Value       string
	UpdatedAt   time.Time
}
