// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppSettingsPrompt struct {
	ID        string
	Name      string
	Value     string
	UpdatedAt time.Time
}
