// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createPromptSetting = `-- name: CreatePromptSetting :one
INSERT INTO settings_prompt (name, value)
VALUES ($1, $2)
RETURNING id, name, value, updated_at
`

type CreatePromptSettingParams struct {
	Name  string
	Value string
}

func (q *Queries) CreatePromptSetting(ctx context.Context, arg CreatePromptSettingParams) (SettingsPrompt, error) {
	row := q.db.QueryRow(ctx, createPromptSetting, arg.Name, arg.Value)
	var i SettingsPrompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptSetting = `-- name: GetPromptSetting :one
SELECT id, name, value, updated_at FROM settings_prompt WHERE name = $1
`

func (q *Queries) GetPromptSetting(ctx context.Context, name string) (SettingsPrompt, error) {
	row := q.db.QueryRow(ctx, getPromptSetting, name)
	var i SettingsPrompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromptSetting = `-- name: UpdatePromptSetting :exec
UPDATE settings_prompt SET value = $1, updated_at = now()
WHERE name = $2
`

type UpdatePromptSettingParams struct {
	Value string
	Name  string
}

func (q *Queries) UpdatePromptSetting(ctx context.Context, arg UpdatePromptSettingParams) error {
	_, err := q.db.Exec(ctx, updatePromptSetting, arg.Value, arg.Name)
	return err
}
