// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createKVSetting = `-- name: CreateKVSetting :one
INSERT INTO app_settings_kv (name, value)
VALUES ($1, $2)
RETURNING id, name, value, updated_at
`

type CreateKVSettingParams struct {
	Name  string
	Value string
}

func (q *Queries) CreateKVSetting(ctx context.Context, arg CreateKVSettingParams) (AppSettingsKv, error) {
	row := q.db.QueryRow(ctx, createKVSetting, arg.Name, arg.Value)
	var i AppSettingsKv
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const getKVSetting = `-- name: GetKVSetting :one
SELECT id, name, value, updated_at FROM app_settings_kv WHERE name = $1
`

func (q *Queries) GetKVSetting(ctx context.Context, name string) (AppSettingsKv, error) {
	row := q.db.QueryRow(ctx, getKVSetting, name)
	var i AppSettingsKv
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKVSetting = `-- name: UpdateKVSetting :exec
UPDATE app_settings_kv SET value = $1, updated_at = now()
WHERE name = $2
`

type UpdateKVSettingParams struct {
	Value string
	Name  string
}

func (q *Queries) UpdateKVSetting(ctx context.Context, arg UpdateKVSettingParams) error {
	_, err := q.db.Exec(ctx, updateKVSetting, arg.Value, arg.Name)
	return err
}
