// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Memory struct {
	ID        string
	Content   string
	SessionID string
	CreatedAt time.Time
}

type MemorySource struct {
	MemoryID  string
	MessageID string
}
