// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const addMemorySource = `-- name: AddMemorySource :exec
INSERT INTO app_notes_memory_sources (memory_id, message_id)
VALUES ($1, $2)
`

type AddMemorySourceParams struct {
	MemoryID  string
	MessageID string
}

func (q *Queries) AddMemorySource(ctx context.Context, arg AddMemorySourceParams) error {
	_, err := q.db.Exec(ctx, addMemorySource, arg.MemoryID, arg.MessageID)
	return err
}

const createMemoryForUser = `-- name: CreateMemoryForUser :one
INSERT INTO app_notes_memories (agent_id, user_id, content, session_id)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_id, user_id, content, session_id, created_at
`

type CreateMemoryForUserParams struct {
	AgentID   string
	UserID    string
	Content   string
	SessionID string
}

func (q *Queries) CreateMemoryForUser(ctx context.Context, arg CreateMemoryForUserParams) (AppNotesMemory, error) {
	row := q.db.QueryRow(ctx, createMemoryForUser,
		arg.AgentID,
		arg.UserID,
		arg.Content,
		arg.SessionID,
	)
	var i AppNotesMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Content,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, agent_id, user_id, content, session_id, created_at FROM app_notes_memories WHERE id = $1
`

func (q *Queries) GetMemory(ctx context.Context, id string) (AppNotesMemory, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i AppNotesMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Content,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemorySources = `-- name: GetMemorySources :many
SELECT message_id FROM app_notes_memory_sources WHERE memory_id = $1
`

func (q *Queries) GetMemorySources(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemorySources, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByAgentAndUser = `-- name: ListMemoriesByAgentAndUser :many
SELECT id, agent_id, user_id, content, session_id, created_at FROM app_notes_memories
WHERE agent_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListMemoriesByAgentAndUserParams struct {
	AgentID string
	UserID  string
}

func (q *Queries) ListMemoriesByAgentAndUser(ctx context.Context, arg ListMemoriesByAgentAndUserParams) ([]AppNotesMemory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByAgentAndUser, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppNotesMemory
	for rows.Next() {
		var i AppNotesMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.UserID,
			&i.Content,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemoriesByAgentAndUser = `-- name: ListRecentMemoriesByAgentAndUser :many
SELECT id, agent_id, user_id, content, session_id, created_at FROM app_notes_memories
WHERE agent_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListRecentMemoriesByAgentAndUserParams struct {
	AgentID string
	UserID  string
	Limit   int32
}

func (q *Queries) ListRecentMemoriesByAgentAndUser(ctx context.Context, arg ListRecentMemoriesByAgentAndUserParams) ([]AppNotesMemory, error) {
	rows, err := q.db.Query(ctx, listRecentMemoriesByAgentAndUser, arg.AgentID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppNotesMemory
	for rows.Next() {
		var i AppNotesMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.UserID,
			&i.Content,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
