// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const addMemorySource = `-- name: AddMemorySource :exec
INSERT INTO memory_sources (memory_id, message_id)
VALUES ($1, $2)
`

type AddMemorySourceParams struct {
	MemoryID  string
	MessageID string
}

func (q *Queries) AddMemorySource(ctx context.Context, arg AddMemorySourceParams) error {
	_, err := q.db.Exec(ctx, addMemorySource, arg.MemoryID, arg.MessageID)
	return err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (content, session_id)
VALUES ($1, $2)
RETURNING id, content, session_id, created_at
`

type CreateMemoryParams struct {
	Content   string
	SessionID string
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory, arg.Content, arg.SessionID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, content, session_id, created_at FROM memories WHERE id = $1
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemorySources = `-- name: GetMemorySources :many
SELECT message_id FROM memory_sources WHERE memory_id = $1
`

func (q *Queries) GetMemorySources(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemorySources, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemories = `-- name: ListMemories :many
SELECT id, content, session_id, created_at FROM memories ORDER BY created_at DESC
`

func (q *Queries) ListMemories(ctx context.Context) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemories = `-- name: ListRecentMemories :many
SELECT id, content, session_id, created_at FROM memories ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentMemories(ctx context.Context, limit int32) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listRecentMemories, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
