// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppSystemConnection struct {
	ConnectionID string
	UserID       string
	WorkspaceID  string
	ConnectedAt  time.Time
}

type AppSystemUser struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AppSystemUserPassword struct {
	UserID       string
	PasswordHash string
	UpdatedAt    time.Time
}

type AppSystemWorkspace struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type AppSystemWorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	JoinedAt    time.Time
}
