// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppSystemConnection struct {
	ConnectionID string
	UserID       string
	ConnectedAt  time.Time
}

type AppSystemUser struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
