// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createConnection = `-- name: CreateConnection :exec

INSERT INTO app_system_connections (connection_id, user_id)
VALUES ($1, $2)
`

type CreateConnectionParams struct {
	ConnectionID string
	UserID       string
}

// Connections
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) error {
	_, err := q.db.Exec(ctx, createConnection, arg.ConnectionID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO app_system_users (email, name, role)
VALUES ($1, $2, $3)
RETURNING id, email, name, role, created_at, updated_at
`

type CreateUserParams struct {
	Email string
	Name  string
	Role  string
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.Role)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM app_system_connections WHERE connection_id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, connectionID string) error {
	_, err := q.db.Exec(ctx, deleteConnection, connectionID)
	return err
}

const getConnectionsByUser = `-- name: GetConnectionsByUser :many
SELECT connection_id, user_id, connected_at FROM app_system_connections WHERE user_id = $1
`

func (q *Queries) GetConnectionsByUser(ctx context.Context, userID string) ([]AppSystemConnection, error) {
	rows, err := q.db.Query(ctx, getConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemConnection
	for rows.Next() {
		var i AppSystemConnection
		if err := rows.Scan(&i.ConnectionID, &i.UserID, &i.ConnectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwner = `-- name: GetOwner :one
SELECT id, email, name, role, created_at, updated_at FROM app_system_users WHERE role = 'owner' LIMIT 1
`

func (q *Queries) GetOwner(ctx context.Context) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, getOwner)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, created_at, updated_at FROM app_system_users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, created_at, updated_at FROM app_system_users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]AppSystemUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemUser
	for rows.Next() {
		var i AppSystemUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
