// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addMembership = `-- name: AddMembership :exec

INSERT INTO app_system_workspace_members (user_id, workspace_id, role)
VALUES ($1, $2, $3)
`

type AddMembershipParams struct {
	UserID      string
	WorkspaceID string
	Role        string
}

// Workspace Members
func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.UserID, arg.WorkspaceID, arg.Role)
	return err
}

const createConnection = `-- name: CreateConnection :exec

INSERT INTO app_system_connections (connection_id, user_id, workspace_id)
VALUES ($1, $2, $3)
`

type CreateConnectionParams struct {
	ConnectionID string
	UserID       string
	WorkspaceID  string
}

// Connections
// TODO: reconsider whether a connection should be bound to a workspace.
// Slack/Discord style is one connection per user, with workspace_id
// carried in each message payload. Current binding forces a reconnect
// when the user switches workspaces and blocks cross-workspace events.
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) error {
	_, err := q.db.Exec(ctx, createConnection, arg.ConnectionID, arg.UserID, arg.WorkspaceID)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO app_system_users (email, name, role)
VALUES ($1, $2, $3)
RETURNING id, email, name, role, created_at, updated_at
`

type CreateUserParams struct {
	Email string
	Name  string
	Role  string
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.Role)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one

INSERT INTO app_system_workspaces (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, deleted_at
`

// Workspaces
func (q *Queries) CreateWorkspace(ctx context.Context, name string) (AppSystemWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i AppSystemWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM app_system_connections WHERE connection_id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, connectionID string) error {
	_, err := q.db.Exec(ctx, deleteConnection, connectionID)
	return err
}

const deleteUserPassword = `-- name: DeleteUserPassword :exec
DELETE FROM app_system_user_passwords WHERE user_id = $1
`

func (q *Queries) DeleteUserPassword(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserPassword, userID)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, email, name, role, created_at, updated_at FROM app_system_users WHERE role = 'admin' LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, getAdmin)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionsByUser = `-- name: GetConnectionsByUser :many
SELECT connection_id, user_id, workspace_id, connected_at FROM app_system_connections WHERE user_id = $1
`

func (q *Queries) GetConnectionsByUser(ctx context.Context, userID string) ([]AppSystemConnection, error) {
	rows, err := q.db.Query(ctx, getConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemConnection
	for rows.Next() {
		var i AppSystemConnection
		if err := rows.Scan(
			&i.ConnectionID,
			&i.UserID,
			&i.WorkspaceID,
			&i.ConnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT workspace_id, user_id, role, joined_at FROM app_system_workspace_members
WHERE user_id = $1 AND workspace_id = $2
`

type GetMembershipParams struct {
	UserID      string
	WorkspaceID string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (AppSystemWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.WorkspaceID)
	var i AppSystemWorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, created_at, updated_at FROM app_system_users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, created_at, updated_at FROM app_system_users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppSystemUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppSystemUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one

SELECT password_hash FROM app_system_user_passwords WHERE user_id = $1
`

// User Passwords
func (q *Queries) GetUserPasswordHash(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at, deleted_at FROM app_system_workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (AppSystemWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i AppSystemWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMembersByWorkspace = `-- name: ListMembersByWorkspace :many
SELECT u.id, u.email, u.name, u.role, u.created_at, u.updated_at, m.role AS workspace_role, m.joined_at
FROM app_system_users u
JOIN app_system_workspace_members m ON m.user_id = u.id
WHERE m.workspace_id = $1
ORDER BY m.joined_at
`

type ListMembersByWorkspaceRow struct {
	ID            string
	Email         string
	Name          string
	Role          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	WorkspaceRole string
	JoinedAt      time.Time
}

func (q *Queries) ListMembersByWorkspace(ctx context.Context, workspaceID string) ([]ListMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByWorkspaceRow
	for rows.Next() {
		var i ListMembersByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceRole,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, created_at, updated_at FROM app_system_users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]AppSystemUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemUser
	for rows.Next() {
		var i AppSystemUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, created_at, updated_at, deleted_at FROM app_system_workspaces
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]AppSystemWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemWorkspace
	for rows.Next() {
		var i AppSystemWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.created_at, w.updated_at, w.deleted_at FROM app_system_workspaces w
JOIN app_system_workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.created_at
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID string) ([]AppSystemWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSystemWorkspace
	for rows.Next() {
		var i AppSystemWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMembership = `-- name: RemoveMembership :exec
DELETE FROM app_system_workspace_members
WHERE user_id = $1 AND workspace_id = $2
`

type RemoveMembershipParams struct {
	UserID      string
	WorkspaceID string
}

func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error {
	_, err := q.db.Exec(ctx, removeMembership, arg.UserID, arg.WorkspaceID)
	return err
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE app_system_workspaces
SET deleted_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE app_system_workspace_members
SET role = $1
WHERE user_id = $2 AND workspace_id = $3
`

type UpdateMembershipRoleParams struct {
	Role        string
	UserID      string
	WorkspaceID string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.Role, arg.UserID, arg.WorkspaceID)
	return err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :exec
UPDATE app_system_workspaces
SET name = $1, updated_at = now()
WHERE id = $2
`

type UpdateWorkspaceNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceName, arg.Name, arg.ID)
	return err
}

const upsertUserPasswordHash = `-- name: UpsertUserPasswordHash :exec
INSERT INTO app_system_user_passwords (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type UpsertUserPasswordHashParams struct {
	UserID       string
	PasswordHash string
}

func (q *Queries) UpsertUserPasswordHash(ctx context.Context, arg UpsertUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, upsertUserPasswordHash, arg.UserID, arg.PasswordHash)
	return err
}
