// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppAgentsProfile struct {
	ID        string
	Name      string
	Soul      string
	Model     string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type AppAgentsWorkspace struct {
	AgentID     string
	WorkspaceID string
	AttachedAt  time.Time
}
