// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO app_agents_profiles (name, soul, model)
VALUES ($1, $2, $3)
RETURNING id, name, soul, model, created_at, updated_at, deleted_at
`

type CreateAgentParams struct {
	Name  string
	Soul  string
	Model string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (AppAgentsProfile, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.Soul, arg.Model)
	var i AppAgentsProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Soul,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, soul, model, created_at, updated_at, deleted_at FROM app_agents_profiles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgent(ctx context.Context, id string) (AppAgentsProfile, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i AppAgentsProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Soul,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, soul, model, created_at, updated_at, deleted_at FROM app_agents_profiles WHERE deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListAgents(ctx context.Context) ([]AppAgentsProfile, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAgentsProfile
	for rows.Next() {
		var i AppAgentsProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Soul,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAgent = `-- name: SoftDeleteAgent :exec
UPDATE app_agents_profiles SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteAgent, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE app_agents_profiles
SET name = $1, soul = $2, model = $3, updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateAgentParams struct {
	Name  string
	Soul  string
	Model string
	ID    string
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.Exec(ctx, updateAgent,
		arg.Name,
		arg.Soul,
		arg.Model,
		arg.ID,
	)
	return err
}
