// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppChatMessage struct {
	ID             string
	SessionID      string
	Role           string
	Content        string
	ToolCalls      pgtype.Text
	ToolCallID     string
	SequenceNumber int32
	ForwardedFrom  *string
	ReplyTo        *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AppChatSession struct {
	ID              string
	UserID          string
	Title           string
	Model           string
	SystemPrompt    string
	ContextWindow   int32
	ContextMessages string
	ContextSummary  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type AppChatSessionMember struct {
	SessionID string
	UserID    string
	Role      string
	JoinedAt  time.Time
}

type AppChatUser struct {
	ID        string
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
