// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (session_id, role, content, tool_calls, tool_call_id, sequence_number, forwarded_from, reply_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, session_id, role, content, tool_calls, tool_call_id, sequence_number, forwarded_from, reply_to, created_at, updated_at
`

type CreateMessageParams struct {
	SessionID      string
	Role           string
	Content        string
	ToolCalls      pgtype.Text
	ToolCallID     string
	SequenceNumber int32
	ForwardedFrom  *string
	ReplyTo        *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.SequenceNumber,
		arg.ForwardedFrom,
		arg.ReplyTo,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.SequenceNumber,
		&i.ForwardedFrom,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (title, user_id, model, system_prompt, context_window, context_messages, context_summary)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, model, system_prompt, context_window, context_messages, context_summary, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	Title           string
	UserID          string
	Model           string
	SystemPrompt    string
	ContextWindow   int32
	ContextMessages string
	ContextSummary  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Title,
		arg.UserID,
		arg.Model,
		arg.SystemPrompt,
		arg.ContextWindow,
		arg.ContextMessages,
		arg.ContextSummary,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.ContextWindow,
		&i.ContextMessages,
		&i.ContextSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, title, model, system_prompt, context_window, context_messages, context_summary, created_at, updated_at, deleted_at FROM sessions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.ContextWindow,
		&i.ContextMessages,
		&i.ContextSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, role, content, tool_calls, tool_call_id, sequence_number, forwarded_from, reply_to, created_at, updated_at FROM messages WHERE session_id = $1 ORDER BY sequence_number
`

func (q *Queries) ListMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.SequenceNumber,
			&i.ForwardedFrom,
			&i.ReplyTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, title, model, system_prompt, context_window, context_messages, context_summary, created_at, updated_at, deleted_at FROM sessions WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Model,
			&i.SystemPrompt,
			&i.ContextWindow,
			&i.ContextMessages,
			&i.ContextSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, title, model, system_prompt, context_window, context_messages, context_summary, created_at, updated_at, deleted_at FROM sessions WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Model,
			&i.SystemPrompt,
			&i.ContextWindow,
			&i.ContextMessages,
			&i.ContextSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE sessions SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET title = $1, model = $2, system_prompt = $3, context_window = $4,
    context_messages = $5, context_summary = $6, updated_at = now()
WHERE id = $7 AND deleted_at IS NULL
`

type UpdateSessionParams struct {
	Title           string
	Model           string
	SystemPrompt    string
	ContextWindow   int32
	ContextMessages string
	ContextSummary  string
	ID              string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.Title,
		arg.Model,
		arg.SystemPrompt,
		arg.ContextWindow,
		arg.ContextMessages,
		arg.ContextSummary,
		arg.ID,
	)
	return err
}
