// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppSkill struct {
	ID          string
	Author      string
	Name        string
	Description string
	WhenToUse   string
	Tags        string
	Version     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
