// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getSkillFromWorkspace = `-- name: GetSkillFromWorkspace :one
SELECT workspace_id, author, name, version, description, when_to_use, tags, installed_at, updated_at FROM app_skills
WHERE workspace_id = $1 AND author = $2 AND name = $3
`

type GetSkillFromWorkspaceParams struct {
	WorkspaceID string
	Author      string
	Name        string
}

func (q *Queries) GetSkillFromWorkspace(ctx context.Context, arg GetSkillFromWorkspaceParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, getSkillFromWorkspace, arg.WorkspaceID, arg.Author, arg.Name)
	var i AppSkill
	err := row.Scan(
		&i.WorkspaceID,
		&i.Author,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.WhenToUse,
		&i.Tags,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const installSkill = `-- name: InstallSkill :one
INSERT INTO app_skills (workspace_id, author, name, version, description, when_to_use, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING workspace_id, author, name, version, description, when_to_use, tags, installed_at, updated_at
`

type InstallSkillParams struct {
	WorkspaceID string
	Author      string
	Name        string
	Version     string
	Description string
	WhenToUse   string
	Tags        string
}

func (q *Queries) InstallSkill(ctx context.Context, arg InstallSkillParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, installSkill,
		arg.WorkspaceID,
		arg.Author,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.WhenToUse,
		arg.Tags,
	)
	var i AppSkill
	err := row.Scan(
		&i.WorkspaceID,
		&i.Author,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.WhenToUse,
		&i.Tags,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillsByWorkspace = `-- name: ListSkillsByWorkspace :many
SELECT workspace_id, author, name, version, description, when_to_use, tags, installed_at, updated_at FROM app_skills
WHERE workspace_id = $1
ORDER BY author, name
`

func (q *Queries) ListSkillsByWorkspace(ctx context.Context, workspaceID string) ([]AppSkill, error) {
	rows, err := q.db.Query(ctx, listSkillsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSkill
	for rows.Next() {
		var i AppSkill
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Author,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.WhenToUse,
			&i.Tags,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uninstallSkillInWorkspace = `-- name: UninstallSkillInWorkspace :exec
DELETE FROM app_skills
WHERE workspace_id = $1 AND author = $2 AND name = $3
`

type UninstallSkillInWorkspaceParams struct {
	WorkspaceID string
	Author      string
	Name        string
}

func (q *Queries) UninstallSkillInWorkspace(ctx context.Context, arg UninstallSkillInWorkspaceParams) error {
	_, err := q.db.Exec(ctx, uninstallSkillInWorkspace, arg.WorkspaceID, arg.Author, arg.Name)
	return err
}

const updateSkillInWorkspace = `-- name: UpdateSkillInWorkspace :exec
UPDATE app_skills
SET version = $4, description = $5, when_to_use = $6, tags = $7, updated_at = now()
WHERE workspace_id = $1 AND author = $2 AND name = $3
`

type UpdateSkillInWorkspaceParams struct {
	WorkspaceID string
	Author      string
	Name        string
	Version     string
	Description string
	WhenToUse   string
	Tags        string
}

func (q *Queries) UpdateSkillInWorkspace(ctx context.Context, arg UpdateSkillInWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateSkillInWorkspace,
		arg.WorkspaceID,
		arg.Author,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.WhenToUse,
		arg.Tags,
	)
	return err
}
