// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO app_skills (author, name, description, when_to_use, tags, version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, author, name, description, when_to_use, tags, version, created_at, updated_at
`

type CreateSkillParams struct {
	Author      string
	Name        string
	Description string
	WhenToUse   string
	Tags        string
	Version     string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.Author,
		arg.Name,
		arg.Description,
		arg.WhenToUse,
		arg.Tags,
		arg.Version,
	)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Name,
		&i.Description,
		&i.WhenToUse,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM app_skills WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, author, name, description, when_to_use, tags, version, created_at, updated_at FROM app_skills WHERE id = $1
`

func (q *Queries) GetSkill(ctx context.Context, id string) (AppSkill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Name,
		&i.Description,
		&i.WhenToUse,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, author, name, description, when_to_use, tags, version, created_at, updated_at FROM app_skills WHERE author = $1 AND name = $2
`

type GetSkillByNameParams struct {
	Author string
	Name   string
}

func (q *Queries) GetSkillByName(ctx context.Context, arg GetSkillByNameParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, getSkillByName, arg.Author, arg.Name)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Name,
		&i.Description,
		&i.WhenToUse,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, author, name, description, when_to_use, tags, version, created_at, updated_at FROM app_skills ORDER BY author, name
`

func (q *Queries) ListSkills(ctx context.Context) ([]AppSkill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSkill
	for rows.Next() {
		var i AppSkill
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Name,
			&i.Description,
			&i.WhenToUse,
			&i.Tags,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE app_skills
SET description = $1, when_to_use = $2, tags = $3, version = $4, updated_at = now()
WHERE id = $5
`

type UpdateSkillParams struct {
	Description string
	WhenToUse   string
	Tags        string
	Version     string
	ID          string
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.Exec(ctx, updateSkill,
		arg.Description,
		arg.WhenToUse,
		arg.Tags,
		arg.Version,
		arg.ID,
	)
	return err
}
